<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Barbaruiva.xyz | OMB </title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css"
          integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
    <script src="https://use.fontawesome.com/77dcf173a3.js"></script>
</head>
<body>
<div class="fluid-container">
    <div class="jumbotron">
        <h1 class="display-3">Online Music Battle</h1>
    </div>
    <style>
        .btn-voto {
            border-radius: 50% ;
            background-color: #ff7fd1;
            color: white;
            width: 100px;
            height: 100px;
            transition: all .5s ease-in-out; }
        .btn-voto:focus { transform: scale(1.3); }

        .btn-voto .fa {
            font-size: 60px;
            top: 50%;
            position: relative;
            transform: translateY(-50%);
        }
        a:hover {
            color: #ffffaa;
        }
    </style>
        <div id="votacao" style="{% if not battle %}display:none; {% endif %}" class="container">
            <div class="row">
                <div class="col-sm-12 col-md-6">
                    <div class="container">
                        <div class="card text-center">
                            <div id="musica1" class="card-header">
                                {{battle.getMusica1.getNome}}
                            </div>
                            <div class="card-body">
                                <a href="{{base_url()}}/1/votar" class="btn btn-voto grow"><i class="fa fa-thumbs-up" aria-hidden="true"></i>
                                </a>
                            </div>
                            <div class="card-footer text-muted">
                                <span id="votos1">{{battle.getMusica1.getVotos}} </span> <span class="octicon thumbsup"></span>votos
                            </div>
                        </div>
                    </div>

                </div>
                <div class="col-sm-12 col-md-6">
                    <div class="container">
                        <div class="card text-center">
                            <div id="musica2" class="card-header">
                                {{battle.getMusica2.getNome}}
                            </div>
                            <div class="card-body">
                                <a href="{{base_url()}}/2/votar" class="btn btn-voto grow"><i class="fa fa-thumbs-up" aria-hidden="true"></i>
                                </a>
                            </div>
                            <div class="card-footer text-muted">
                                <span id="votos2">{{battle.getMusica2.getVotos}}</span> votos
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
        <div style="{% if battle %}display:none; {% endif %}" id="semVotacao">
            <h3>Nenhuma votação em andamento.</h3>
        </div>
</div>
<script>
    function atualiza() {
        $.post("{{base_url()}}/", function (data, status, xhr) {
            if (data != null && xhr.status==200){


                    var musicas = Object.keys(data.musicas);
                if (musicas.length > 0) {
                    $("#musica1").html(musicas[0]);
                    $("#votos1").html(data.musicas[musicas[0]]);
                    $("#musica2").html(musicas[1]);
                    $("#votos2").html(data.musicas[musicas[1]]+"");

                }else{
                    //sem votação
                }
            }

        })
    }

    function onClickBtn(event) {
        event.preventDefault();
        $.post(this.href, function (data, status) {
            //remove foco para remover a animação
            $(".btn-voto").blur();
        });
    };


    $('.btn-voto').on('click', onClickBtn);
    setInterval(atualiza, 1000);
</script>
</body>
</html>
